"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Product_1 = require("./Product");
var Cart_1 = require("./Cart");
var cart = new Cart_1.Cart();
var product1 = new Product_1.Product(1, 'product1', 11000);
var product2 = new Product_1.Product(2, 'product2', 200);
var product3 = new Product_1.Product(3, 'product3', 50);
cart.addProduct(product1);
cart.addProduct(product2);
cart.addProduct(product3);
cart.showCart();
